SUPABASE_URL_PROD=https://lmhkgxzfqzryocbjqcfi.supabase.co
SUPABASE_KEY_PROD=sb_publishable_QMa1RQsaJ1tiktmZsyyYag_l3ysMHOp

SUPABASE_URL_DEV=http://192.168.1.103:54321
SUPABASE_KEY_DEV=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH

